import './globals.css'
import type { Metadata } from 'next'

import { ClerkProvider } from '@clerk/nextjs'

import { ThemeProvider } from '@/components/theme-provider'

export const metadata: Metadata = {
    title: 'NextJs Boilerplate',
    description: 'Generated by Ozan Yildirim',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                        <div className="relative flex min-h-screen flex-col">
                            <div className="flex-1">{children}</div>
                        </div>
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    )
}
