import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'NextJs Boilerplate',
    description: 'Generated by Ozan Yildirim',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head />
            <body className="min-h-screen bg-background font-sans antialiased">
                <div className="relative flex min-h-screen flex-col">
                    <div className="flex-1">{children}</div>
                </div>
            </body>
        </html>
    )
}
